### ISSUE TITLE
Fully utilise appearance features during Bayesian updates

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/BayesianTracker#108]
+ [x] Allow objects to have features
+ [x] Split Bayesian updates during track linking, to allow motion and feature based updates
+ [x] Provide option to track using motion, features or both
+ [ ] Allow the hypothesis engine to use features when performing optimisation
+ [x] Add documentation

Current WIP in branch: https://github.com/quantumjot/BayesianTracker/tree/visual-features

**Comment by lupinthief** [comment]
Icebergs toy dataset here: https://github.com/lupinthief/tracking_btrack

**Comment by quantumjot** [comment]
@lupinthief - currently the tracker always uses the motion model, but the features are optional. Should we make both optional (but with the requirement to have at least one of them)?

**Comment by lupinthief** [comment]
@quantumjot - If that isn't too tricky that would mean I could focus on the visual features to begin with then think about what sort of motion model might be best suited - the more I think about it getting the flow field representation right might make more physical sense in terms of the processes of motion with icebergs than trying to adapt the motion model.

**Comment by quantumjot** [comment]
Latest update allows you to specify which updates to perform (either `motion`, `visual` or both). API has changed a little bit because of this:

```python
with btrack.BayesianTracker() as tracker:
  ...
  tracker.track(tracking_updates=["visual",])
```

 Keen to know what you make of it!

**Comment by quantumjot** [comment]
@lupinthief - should work with Python 3.7 now.
