### ISSUE TITLE
Btrack configuration

### ISSUE THREAD

**Issue by SChoi97** [quantumjot/BayesianTracker#12]
First of all, thank you for this great resource! It has been a great help in single-cell tracking of my cells.

As the cells in my videos behave quite differently to those that this software was initially designed for (as shown in the videos), I have had to toggle values in the cell_config file. To do this, I have inferred the roles of parameters (such as 'lambda_dist' etc.) by tweaking them and observing changes in tracks on Napari. However, if all goes well, as I would like to use this analysis in a near-future publication, it would be great if I could make sure of what I have actually done (perhaps I have tweaked values that I should not have?). 

It would be great to have a brief rundown of what each parameter does as well as what would be expected if each parameter was increased/decreased. 

Again, thanks for the great resource!

**Comment by quantumjot** [comment]
Hi @SChoi97 - thanks for your feedback. It's great to hear that you're finding `btrack` (and the new napari `Tracks` layer) useful!

There is some information about what the model parameters represent in the wiki:
* https://github.com/quantumjot/BayesianTracker/wiki/2.-Configuration
* https://github.com/quantumjot/BayesianTracker/wiki/5.-Optimizer

We'll try to add some more detailed information to the docstrings in the library too.

**Comment by SChoi97** [comment]
Hi @quantumjot thank you very much! I have checked out the wiki and it is very helpful thanks. Apologies, I should have checked there before submitting this.

Thank you for your help!
