### ISSUE TITLE
Add installation instructions for documentation developers

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/BayesianTracker#126]
I'm not sure, but do we want to mention that it's `pip install -e .[docs]` if developing documentation anywhere?

_Originally posted by @paddyroddy in https://github.com/quantumjot/BayesianTracker/pull/121#discussion_r863607817_

**Comment by dstansby** [comment]
Yes, it would be good to put this in `docs/dev_guide/index.rst` - @paddyroddy perhaps you could do this as you've got it fresh in your head what needs to be done to be able to install/develop the docs?
