### ISSUE TITLE
Explanation on the `envlist` syntax in `tox.ini`

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/BayesianTracker#148]
I assume that PR #115 works okay, but an explanation on how this syntax works would be welcomed https://github.com/quantumjot/BayesianTracker/pull/115#discussion_r884939829

**Comment by dstansby** [comment]
See https://tox.wiki/en/latest/config.html#tox-environments for general documentation on specifying environments, and I added a specific explanation on the original comment, so I think this can be closed.
