### ISSUE TITLE
Issue decoding h5 files

### ISSUE THREAD

**Issue by tsloan1377** [quantumjot/BayesianTracker#19]
Hello, I am building a tool to import cell tracking files, process them in Python and visualize them in Blender. I am having some issues decoding the h5 files exported by btrack. 

Following the file structure from dataio.py,  I understand that the tracks 'map' array is a (K x 2) array of indexes to the 'tracks' array, and that using these indices in the 'tracks' array allows us to extract the relevant indices for the 'coords' array.

Where I am a bit lost is why there are negative integers included in the tracks array, and how they relate to the size of the dummy dataset?
For every dataset queried:

`abs(np.min(tracks)) == dummies.shape[0]
`

For example, a sample slice of 'tracks' using 'map' indices
looks like this:

`
[ 1545  2335  3635  4695  5727  6774  7787  8851  9906 10983 -1252 12986 14045 15066 16124 17145 18194 19229 20264 21266 22015 -1253 24251 25261 26018 27052 28443 29478 30546 31581 32653 33688 -1254 35627 36369 37463 38801 39846 40875 41946 42986 44003]
`

What is strange is how the pattern of negative values is such that they are decreasing by 1 each time, until they reach a minimum value equal to the number of rows in the 'dummies' array. 

Using these indices to slice the 'coords' array leads to discontinuities of the otherwise temporally continuous slices of the dataset.

For example, here is the corresponding slice from 'coords' from the tracks indices above:

```
[[  1.       691.25354  305.169     56.560562   0.      ]
 [  2.       690.2381   306.49524   50.862858   0.      ]
 [  3.       679.69147  315.4468    53.95213    0.      ]
 [  4.       671.06665  317.68332   55.6025     0.      ]
 [  5.       658.7258   314.58566   60.326637   0.      ]
 [  6.       654.0179   307.42856   60.498215   0.      ]
 [  7.       657.6908   306.5987    59.42171    0.      ]
 [  8.       656.00934  306.84113   60.632942   0.      ]
 [  9.       656.31055  311.1738    60.31111    0.      ]
 [ 10.       656.6334   308.63986   60.369453   0.      ]
 [237.       613.4513   564.4992    57.711514   0.      ]
 [ 12.       658.06006  307.46738   58.93825    0.      ]
 [ 13.       663.02563  307.453     59.71154    0.      ]
 [ 14.       662.3555   308.1111    59.263332   0.      ]
 [ 15.       661.60986  308.29596   59.485428   0.      ]
 [ 16.       661.6381   307.41904   59.175713   0.      ]
 [ 17.       663.1128   309.82706   59.609776   0.      ]
 [ 18.       658.50543  306.27716   60.4125     0.      ]
 [ 19.       655.3111   304.77777   58.956665   0.      ]
 [ 20.       655.0373   306.6087    59.807144   0.      ]
 [ 21.       654.80743  306.40994   60.79286    0.      ]
 [237.       402.58563  561.1381    57.830387   0.      ]
 [ 23.       655.58093  307.2614    59.981327   0.      ]
 [ 24.       662.2381   307.25714   60.95       0.      ]
 [ 25.       654.6695   309.15967   56.97815    0.      ]
 [ 26.       655.3333   310.1839    59.918964   0.      ]
 [ 27.       661.25793  312.62442   59.680317   0.      ]
 [ 28.       659.13513  313.27927   60.483784   0.      ]
 [ 29.       657.9659   310.66476   60.061363   0.      ]
 [ 30.       657.5599   307.24295   59.415318   0.      ]
 [ 31.       658.72034  307.2523    59.174316   0.      ]
 [ 32.       658.81067  305.4852    60.181065   0.      ]
 [237.       107.055176 557.10345   60.258415   0.      ]
 [ 34.       657.86707  306.13925   60.942722   0.      ]
 [ 35.       657.526    305.88962   60.46461    0.      ]
 [ 36.       657.0847   307.0904    60.579662   0.      ]
 [ 37.       658.86957  305.21738   60.6        0.      ]
 [ 38.       658.6667   307.30362   58.786633   0.      ]
 [ 39.       658.77563  307.19232   59.037018   0.      ]
 [ 40.       659.3985   304.21054   59.661655   0.      ]
 [ 41.       658.49854  306.18552   58.82       0.      ]
 [ 42.       659.33496  306.68216   57.882397   0.      ]]

```

Thanks in advance for any advice you can provide,

**Comment by quantumjot** [comment]
Hi @tsloan1377 - this sounds really exciting - I'd be really keen to see the output when you're done!

Re: file format - the key issue here is that the negative indices signal that these are dummies (i.e. inserted during tracking due to a missing observation etc.) - therefore they do not exist in the `coords` array. These numbers are indices into the `tracks\obj_type_{}\dummies` array, so an index of `-1252` means to use the dummy from row `1251`. You can see that here:

https://github.com/quantumjot/BayesianTracker/blob/f17a8701f6190b49d86faf834c3512c6d3240ae0/btrack/dataio.py#L493-L496

In case you want a simpler way to read the files, you can also use the `HDF5FileHandler` directly. It provides some convenience functions to enable users to easily read the files again, e.g.:

```python
from btrack.dataio import HDF5FileHandler

with HDF5FileHandler('/path/to/file.h5', 'r') as h:
    tracks = h.tracks

# convert the first track to a numpy array
track_as_numpy_array = tracks[0].to_array()

# or convert to a Pandas compatible dictionary
track_as_dict = tracks[0].to_dict()
```

Hope that helps!

**Comment by tsloan1377** [comment]
Great, thanks @quantumjot that fixed it perfectly.
I had suspected that's what the negative values encoded, but the "abs() - 1" was the missing element from my previous attempts.

**Comment by tsloan1377** [comment]
I’ve reopened this issue as I have a followup question for decoding the h5 files when additional metrics are included, in this case regionprops.

I’m using Python with h5py to unpack the h5 files produced by Bayesian Tracker. 
When the RegionProps are included with the h5 files, they can be found from the hierarchy in

```
# Where f is the h5py file, and prop is the regionprop of interest:
f = h5py.File(path)
f['objects']['obj_type_1']['properties'][prop]
```
This returns an array with the same length as the coordinates, such that:

```
    prop = 'area' # Or any other included regionprop
    coords = f['objects']['obj_type_1']['coords']
    props = f['objects']['obj_type_1']['properties'][prop]
    print(coords.shape[0] == props.shape[0] )  
```

Evaluates as True.
    
I’m a bit confused about how to access these regioprops values, with respect to skipped values, ‘dummies’. I would like to create a 2d dataframe where each row is a cell at a timepoint, and includes its position and regionprops values.
 From your previous answer, I’ve understood that the missed observation positions (inferred) are inserted as dummies, and the inserted values are contained in:
`f['tracks']['obj_type_1']['dummies'] `

I am confused about when the regionprops are included and stored in the h5 file, whether they are inferred for the missing frames, or skipped. Do I understand well that since the length of the arrays for props and coords are the same, that there is no insertion of 'inferred' or 'dummy' values for the regionprops measurements?

I’ve included the code I built to extract the positions from the coordinates and the dummies below, to provide a bit of context for what I’m trying to do for regionprops as well. 

```
# Creating a minimal code example for extracting tracking data from the h5 file:

# These are numpy arrays extracting from the h5 contents of the same name. 
tmap = h5_data['tmap'] # f['tracks']['obj_type_1']['map']
coords = h5_data['coords'] # f['objects']['obj_type_1']['coords']
dummies = h5_data['dummies'] # f['tracks']['obj_type_1']['coords']
ttracks = h5_data['ttracks'] # f['tracks']['obj_type_1']['tracks']

coord_list = []
for i in range(tmap.shape[0]):

    this_vect = ttracks[tmap[i,0]:tmap[i,1]]
    assert len(this_vect) > 0, 'Zero length element of ttracks found.'

    if(len(this_vect) > min_pts):

        coord_slice = coords[this_vect,:]
        negs = this_vect[this_vect < 0]
        neg_ids = np.where(this_vect < 0)

        if len(negs) > 0:
            dummy_slice = dummies[abs(negs)-1,:]

            # Add the dummy slice to the coord_slice
            coord_slice[neg_ids,:] = dummy_slice

        coord_slice = np.c_[coord_slice, np.full(coord_slice.shape[0],i)] # Add index as column


    coord_list.append(coord_slice)

coord_array = np.vstack(coord_list)

h5_df = pd.DataFrame(data=coord_array,columns=['frame', 'x', 'y', 'z', '_', 'particle'])
h5_df.sort_values(['frame', 'particle'], ascending=[True, True], inplace=True)

```

I hope my question is clear, let me know if I can be more precise.
Thanks in advance,

**Comment by quantumjot** [comment]
Hi @tsloan1377 - the `properties` have the same arrangement as the objects, so there should be a 1:1 mapping between object and property. For dummy objects, there are no properties, since there is no associate measurement.  It's up to you how you want to deal with that (e.g. interpolation, using the last known value etc.)

You can also use this util function to build the table that you're interested in:

https://github.com/quantumjot/BayesianTracker/blob/ac397675a425bf4abe6d9c09fd65f80072bf4950/btrack/utils.py#L295-L324

It will take care of all of this, including adding interpolated values if you want them.

**Comment by tsloan1377** [comment]
Thanks @quantumjot , that clears it up for me.
