### ISSUE TITLE
can not find setup.py

### ISSUE THREAD

**Issue by cz19860416** [quantumjot/BayesianTracker#193]
When I used the script build.sh to build the program. At last step, pip install -e .
It prints" Directory '.' is not installable. File 'setup.py' not found."  , How can i solve this, thank you in advance...

**Comment by quantumjot** [comment]
Hi @cz19860416 - did you manage to sort this out? I think you will need to upgrade your version of `pip`?

**Comment by paddyroddy** [comment]
Hey @cz19860416, there's been a few changes since you raised this, so I'm going to close. Please feel free to re-open if needed.
