### ISSUE TITLE
How does this repo play with the Lowe Lab project board if a separate organisation?

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/BayesianTracker#202]
Needs investigation

**Comment by quantumjot** [comment]
It works!

**Comment by paddyroddy** [comment]
So I've manually added every issue to the project board by clicking on the ➕ and then typing, e.g. `https://github.com/quantumjot/BayesianTracker/issues/4`. However, if it was truly linked then we'd be able to do like this 
![image](https://user-images.githubusercontent.com/15052188/223765371-aff48b4f-9a84-4e88-b63c-3f5e030d3999.png)

Now that #201 is merged, it means all future will go there, so from my point of view this isn't important any more.

If you do want to link it, it seems possible here https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/linking-a-repository-to-a-project-board, but I don't think I can as I'm not an admin.

Otherwise, feel free to close this issue.

**Comment by paddyroddy** [comment]
![image](https://user-images.githubusercontent.com/15052188/223766119-84a0dcde-5324-4ec2-a3c7-926b9bebbb3d.png)
![image](https://user-images.githubusercontent.com/15052188/223766167-38a93301-c2fa-4f9f-b2f0-542586340aa5.png)
Also, you can see it isn't linked here.

**Comment by paddyroddy** [comment]
One other downside of being separate to the organisation is the fact that we can't transfer issues. But this isn't a major issue. Will close for now, but food for thought.
