### ISSUE TITLE
Make a segmentation to centroids utility function

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/BayesianTracker#21]
Would be good to add a utility function that takes the output of a segmentation algorithm and creates the input for `btrack`.

_e.g._:  https://github.com/quantumjot/sequitr/issues/1#issuecomment-818803126

**Comment by quantumjot** [comment]
@laureho - are you interested in testing this?

**Comment by laureho** [comment]
yes, gladly! is the PR ready for testing?

**Comment by quantumjot** [comment]
Weeelll, I think it's almost done - but it's good to check with other people. You'll need to install btrack from the branch to test it:

```
pip install git+https://github.com/quantumjot/BayesianTracker.git@segmentation-to-objects
```

There is an example in the examples folder for the branch. Your feedback would be very welcome. You can also directly do regionprops now, and the details get saved directly to the objects and h5 files etc....

**Comment by quantumjot** [comment]
Here's the notebook with how to use:
https://github.com/quantumjot/BayesianTracker/blob/segmentation-to-objects/examples/segmentation_to_btrack_to_napari.ipynb

**Comment by quantumjot** [comment]
And these are the docstrings so you can see what's going on:
https://github.com/quantumjot/BayesianTracker/blob/1a0e50097b6570641bb4b05f8744aa87e382014a/btrack/_localization.py#L94-L124

**Comment by quantumjot** [comment]
@morriso1 - this PR (#22) may be useful to you too - let me know if you have any feedback!

**Comment by laureho** [comment]
@quantumjot I was closely following the PR as you were working on it 😏 very happy to see this! I'll give feedback once I get to test it
