### ISSUE TITLE
lineage tree ignores multiple parents

### ISSUE THREAD

**Issue by will-moore** [quantumjot/BayesianTracker#216]
With this sample, I have a track that splits into 2 and then they join back into one.

```
viewer = napari.Viewer()
tracks = [
    [0, 1, 50.5, 7.4],
    [0, 2, 50.3, 59.3],
    [1, 3, 73.2, 100.6],
    [1, 4, 75.2, 150.3],
    [2, 3, 13.1, 110.4],
    [2, 4, 14.8, 150.7],
    [3, 5, 54.4, 200.5],
    [3, 6, 52.1, 250.4],
]

graph = {2: [0], 1:[0], 3:[1, 2]}
properties = {"t": [t[1] for t in tracks], "value": [t[3] for t in tracks]}

viewer._add_layer_from_data(tracks, {'graph': graph, 'properties': properties}, "tracks")
napari.run()
```

This shows up correctly on the viewer, but on the lineage tree, the track `3` is shown as only having a single parent:

![Screenshot 2023-03-09 at 09 37 00](https://user-images.githubusercontent.com/900055/223982308-cb96f542-f3cf-4b50-88fc-380452401dbf.png)

Also, the plot at the bottom of the right panel suggests there might be some way to plot the 'properties' of points over time?
Is that right, and if so, how can I get it to show the "value" property in my example?

 Thanks!

**Comment by will-moore** [comment]
Sorry, I realise this is the wrong repo - moving to https://github.com/lowe-lab-ucl/arboretum...

**Comment by will-moore** [comment]
Oh, it looks like this has been moved automatically, to the right location?

**Comment by paddyroddy** [comment]
No, it got moved to a project board from the same organisation. Would you mind opening it on the https://github.com/lowe-lab-ucl/arboretum repo? I can do it otherwise

**Comment by will-moore** [comment]
OK, I'll move it - thx

**Comment by paddyroddy** [comment]
Thanks!
