### ISSUE TITLE
Request for a more thorough description of input format.

### ISSUE THREAD

**Issue by loomcode** [quantumjot/BayesianTracker#3]
Are all of the entries for a JSON object required?  If I'm only interested in spacial tracking (not lineages, or other states), do I need to indicate "label", "states", "probability", or "time"? 

{
  "Object_203622": {
    "x": 554.29737483861709,
    "y": 1199.362071438818,
    "z": 0.0,
    "t": 862,
    "label": "interphase",
    "states": 5,
    "probability": [
      0.996992826461792,
      0.0021888131741434336,
      0.0006106126820668578,
      0.000165432647918351,
      4.232166247675195e-05
    ],
    "dummy": false
  }
}

**Comment by quantumjot** [comment]
I'm in the process of adding more info about importing data on the wiki pages:
[https://github.com/quantumjot/BayesianTracker/wiki/3.-Importing-data](https://github.com/quantumjot/BayesianTracker/wiki/3.-Importing-data)

A minimum specification (if you don't care about states/lineages) would be:
```json
{
"Object_203622": 
  {
    "x": 554.29737483861709,
    "y": 1199.362071438818,
    "z": 0.0,
    "t": 862,
    "label": 0,
    "states": 1,
    "dummy": false
  }
}
```

`t` is just a time index to be used to order the objects for tracking through time.
