### ISSUE TITLE
add more detail to `CONFIGURATION.md`

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/BayesianTracker#34]

**Comment by quantumjot** [comment]
@AbigailMcGovern - Hi!

We're trying to update some of the [documentation](CONFIGURATION.md) around `btrack` and were wondering if you might consider contributing some of your *wonderful* guide (https://github.com/jni/pia-tracking/blob/master/btrack_notes.md) for this?

**Comment by AbigailMcGovern** [comment]
Hi @quantumjot!

Absolutely, I'd be happy to help! I'd be very glad to know it was getting some use. I'm quite busy at the moment (preparing for my confirmation) but should have some time to help out soon 😄

**Comment by quantumjot** [comment]
Closing this in favor of #60
