### ISSUE TITLE
Mask labels not stored when using `segmentation_to_objects`

### ISSUE THREAD

**Issue by laureho** [quantumjot/BayesianTracker#36]
The recently implemented `segmentation_to_objects` function (found [here](https://www.github.com/quantumjot/BayesianTracker/tree/master/btrack%2F_localization.py)) doesn't store the mask labels, e.g. individual cell states, which means these can't be used as additional input for the tracking step.

**Comment by quantumjot** [comment]
Good catch @laureho - we could add another option to the function to do this:

https://github.com/quantumjot/BayesianTracker/blob/20921d4b63455cb53279cdb2adc62d6fee7a2f3c/btrack/_localization.py#L105-L116

something like `use_classification_labels`?

**Comment by laureho** [comment]
Yes that'd work. Let's see, I might try to implement the change and submit a PR.
