### ISSUE TITLE
[FEATURE REQUEST] Min/max values for numeric `napari` widgets should be specified

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/BayesianTracker#366]
For [QSpinBox](https://doc.qt.io/qt-6/qspinbox.html#maximum-prop) and [QDoubleSpinBox](https://doc.qt.io/qt-6/qdoublespinbox.html#maximum-prop) the minimum to maximum range is 0-99 and 0-99.99 respectively. We should allow acceptable ranges (or at least sensible ranges).

This has been done already for some as seen here https://github.com/quantumjot/btrack/blob/8e4da110c9662d7993f58753c1d7e7dd22e09a3a/btrack/napari/widgets/_motion.py#L20

It is not sufficient to only do it in `pydantic`. The widget would still allow you to go beyond that.

**Comment by quantumjot** [comment]
Some default ranges:

Max search radius 0-1000
Max lost 0-10
P(not track) 0-1
Accuracy 0.1-10
P 0-500
Q 0-500
R 0-500

**Comment by paddyroddy** [comment]
There are others, but I'll close this once #376 is merged
