### ISSUE TITLE
last frame missing from tracks

### ISSUE THREAD

**Issue by marx-alex** [quantumjot/BayesianTracker#41]
Hi,
I just found out about btracker some days ago and I would really like to use it in my project. Since now, it works pretty well and it makes a lot of fun to work with. Thank you for that!
However, I noticed an odd behavior to which I have not yet found a work around. Every time I am tracking cells, somehow the last frame is missing from all tracks. Here is an example:

Let there be one object in 7 frames (t0 - 6):
```
x = np.array([200, 201, 202, 203, 204, 207, 208])
y = np.array([503, 507, 499, 500, 510, 515, 518])
t = np.array([0, 1, 2, 3, 4, 5, 6])
z = np.zeros(x.shape)

objects = {'x': x,
           'y': y,
           'z': z,
           't': t}

objects = btrack.dataio.objects_from_dict(objects)
```

I track this object:
```
with btrack.BayesianTracker() as tracker:

    tracker.configure_from_file('tracker_config.json')

    tracker.max_search_radius = 100

    tracker.append(objects)
    tracker.frame_range = (0, 48)

    # set the volume (Z axis volume is set very large for 2D data)
    tracker.volume=((0, 2048), (0, 2048), (-1e5, 1e5))

    # track them (in interactive mode)
    tracker.track() #(step_size=100)

    # generate hypotheses and run the global optimizer
    tracker.optimize()

    tracks = tracker.tracks
```

The output is:
`tracks[0]`
<html>
<body>

ID | t | x | y | z | parent | root | state | generation | dummy
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 0 | 200.0 | 503.0 | 0.0 | 1 | 1 | 5 | 0 | False
1 | 1 | 201.0 | 507.0 | 0.0 | 1 | 1 | 5 | 0 | False
1 | 2 | 202.0 | 499.0 | 0.0 | 1 | 1 | 5 | 0 | False
1 | 3 | 203.0 | 500.0 | 0.0 | 1 | 1 | 5 | 0 | False
1 | 4 | 204.0 | 510.0 | 0.0 | 1 | 1 | 5 | 0 | False
1 | 5 | 207.0 | 515.0 | 0.0 | 1 | 1 | 5 | 0 | False

</body>
</html>

My expectation was, that the last frame (t=6) would also be in the track. This behavior appears every time I use btracker.

Is this behavior intentional and if so, what is the reason?
Is there any possibility to include also the last frame in the tracks?

Thank you!

PS: I use the example configuration file.

**Comment by quantumjot** [comment]
Hi @marx-alex - thanks for the report. This looks like a bug has crept in somewhere. We'll take a look!

**Comment by quantumjot** [comment]
Hi @marx-alex - I just pushed a fix for this to the main repo (not the pypi version), and added your code above as a test.  Let me know if this fixes things for you!

**Comment by marx-alex** [comment]
Thank you @quantumjot! This fixes exactly what I had meant!

**Comment by kevinjohncutler** [comment]
@quantumjot This bug appears to have re-emerged in the latest repo version 0.4.3.

**Comment by quantumjot** [comment]
Hi @kevinjohncutler - thanks for the bug report. Can I ask whether the tests pass for you locally? If they pass, but you still don't get expected behavior with your data, coud I trouble you to open a new issue and describe how it's failing? Thanks!

**Comment by kevinjohncutler** [comment]
@quantumjot Sorry for the delay. Yes, all tests pass locally. I will follow up with a new issue.
