### ISSUE TITLE
Add functionality so that octopuslite-loader style dask arrays are accepted for localisation

### ISSUE THREAD

**Issue by nthndy** [quantumjot/BayesianTracker#47]
https://github.com/quantumjot/BayesianTracker/blob/1bb849081b04921cfe5164761c1cb789dc13fcd4/btrack/_localization.py#L170

Need to fix this error `TypeError: Segmentation of type <class 'dask.array.core.Array'> not accepted.` by expanding localisation to accept dask arrays used in segment-classify-track pipeline. I can give this a go if you want @quantumjot ?

**Comment by quantumjot** [comment]
Sounds great! Go for it!
