### ISSUE TITLE
add ternary segmentation input for localisation step

### ISSUE THREAD

**Issue by nthndy** [quantumjot/BayesianTracker#55]
So multi-class segmentation masks are accepted

**Comment by nthndy** [comment]
https://github.com/quantumjot/BayesianTracker/blob/0be7225f958b75540ec6957622c9dd6b96f809bb/btrack/_localization.py#L59 referencing this

**Comment by nthndy** [comment]
@quantumjot shall i add ternary option or more wider N-ary option in case more than two classes...? in fact do we really need to check if its binary, ternary at all? cant we just pass the segmentation through the label function without checking

**Comment by nthndy** [comment]
actually @KristinaUlicna just informed me that we shd keep the binary option as it can handle boolean arrays which is faster for big data sets and is generally a good idea to not meddle with preexisting functionality

**Comment by nthndy** [comment]
so i will add something that checks if the labels are unique but the best ive got so far is something along the lines of `label(x).max() is not np.unique(x).max()` which doesnt seem v neat fix

**Comment by nthndy** [comment]
(or just `x.max()` for that matter...)

**Comment by quantumjot** [comment]
I just want to draw your attention to #36 too. In that, @laureho was asking that the actual labels stored in the segmentation (i.e. ternary etc..) become object properties. That would be useful to you too @nthndy as you could use them as cell type markers.

**Comment by nthndy** [comment]
@quantumjot is there any particular reason this is a tuple? https://github.com/quantumjot/BayesianTracker/blob/0be7225f958b75540ec6957622c9dd6b96f809bb/btrack/_localization.py#L35 
Due to its tuple immutability (tuputability, if you like) it means I have to supply the property of class id assignment as a whole other parameter in https://github.com/quantumjot/BayesianTracker/blob/0be7225f958b75540ec6957622c9dd6b96f809bb/btrack/_localization.py#L105 
If it were not a tuple we could just add an extra `class id` argument to `properties` which I would then delete after use, which seems tidier from a user perspective imo

**Comment by nthndy** [comment]
also currently means that https://github.com/quantumjot/BayesianTracker/blob/0be7225f958b75540ec6957622c9dd6b96f809bb/btrack/_localization.py#L168 doesn't actually get deleted
