### ISSUE TITLE
Tuple `segmentation_to_objects` properties are immutable

### ISSUE THREAD

**Issue by nthndy** [quantumjot/BayesianTracker#57]
https://github.com/quantumjot/BayesianTracker/blob/0be7225f958b75540ec6957622c9dd6b96f809bb/btrack/_localization.py#L168 doesn't actually get deleted

_Originally posted by @nthndy in https://github.com/quantumjot/BayesianTracker/issues/55#issuecomment-1031847123_

**Comment by quantumjot** [comment]
Good catch. We should probably use a set internally, and then pass the tuple to scikit-image
