### ISSUE TITLE
recreate Tracklet object from saved tracks

### ISSUE THREAD

**Issue by ElpadoCan** [quantumjot/BayesianTracker#71]
Hi, thanks for the great software! 

I have a quick question, I see that I can save the tracks using the `to_dict()` method of the `Tracklet` class and saving to JSON, but I was wondering how do I recreate the `Tracklet `object from the saved tracks? Thanks! 

EDIT: I just tried to save to JSON and I get the following error
`TypeError: Object of type ndarray is not JSON serializable`

I know I could probably convert to lists, but I guess the question is more like how do you recommend I save the tracks and how do I read them back into `btrack`? Thanks

**Comment by quantumjot** [comment]
Hi @ElpadoCan - this is a good question! We're actually trying to improve the documentation at the moment.

So... although you can export the tracklets with the `to_dict()` method, this isn't the preferred way of doing it, as we don't have a corresponding `from_dict()` method (although this would be a nice PR).

Usually the way we do it is to use the HDF5 exporter:

```python
with btrack.BayesianTracker() as tracker:
  ...
  tracker.export(filename, obj_type="obj_type_1")
```

then, if you want to reload the data in another session (and effectively recreate the `Tracklet` objects), you can do this:

```python
with btrack.dataio.HDF5FileHandler(filename, 'r') as reader:
  tracklets = reader.tracks
```

`tracklets` should then be a list of `Tracklet` objects.

Related #46

**Comment by quantumjot** [comment]
Great - I'll keep this issue open while you try it out!

**Comment by ElpadoCan** [comment]
Ok it worked thank you very much! I got AssertionError if I used a filename like `test.h5` but I solved it with `./test.h5` since it wants to check if the parent folder exists. I don't plan to use relative paths anyway in my application so it's fine for me! Thanks!
