### ISSUE TITLE
Make it possible to `pip install btrack` directly on M1 mac

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/BayesianTracker#74]
Tested in a fresh `conda` environment. One cannot simply `pip install btrack` as it struggles to build `h5py` and in turn `cvxopt`.

Thus, to install at the moment:
```
conda create -n bayesian-tracker python=3.9 -y
conda activate bayesian-tracker
conda install cvxopt h5py -y
pip install btrack
```

We either need to document this or fiddle with `setup.py` to address this.

**Comment by quantumjot** [comment]
Does the existing `environment.yml` work for this?

**Comment by paddyroddy** [comment]
If one then does `pip install btrack` then yes. However, my view would be if its own `PyPI` as `pip install btrack` but you are forced to use `conda` then it's not really a solution. Like for example, I didn't think to check if there was one

**Comment by paddyroddy** [comment]
For now, I have created #76 which addresses the steps to work on M1. I'll rename this issue to our ultimate desire to be able to simply run `pip install btrack` on M1

**Comment by dstansby** [comment]
To leave a paper trail, one blocker is that there are no binaries for `pyqt5` (required for `napari`) on PyPI (or conda-forge).

**Comment by paddyroddy** [comment]
> To leave a paper trail, one blocker is that there are no binaries for `pyqt5` (required for `napari`) on PyPI (or conda-forge).

`napari` isn't a requirement for `BayesianTracker` @dstansby , so the recent `pyqt` conda update isn't any help. 

I still have to do what it says at the top (except it no longer seems to require `h5py`)
```
conda create -n bayesian-tracker python=3.9 -y
conda activate bayesian-tracker
conda install cvxopt -y
pip install btrack
```

**Comment by dstansby** [comment]
Ah, I guess that's becuase you need `cvxopt` from conda on an M1 mac, which I already discovered in https://github.com/quantumjot/BayesianTracker/commit/91c6cf5d703d41820564e2e00f019e8d16b36871

I think the action here is to add the steps in the above commend to the btrack docs.

**Comment by paddyroddy** [comment]
Is there a way we can do this with `setup.cfg`?

**Comment by dstansby** [comment]
No, `setup.cfg` is not used by conda so can't be used to specify conda dependencies.
