### ISSUE TITLE
NameError: name 'csvfile' is not defined

### ISSUE THREAD

**Issue by loomcode** [quantumjot/BayesianTracker#8]
It looks like there's a typo in dataio.py

```
    with open(filename, 'r') as csv_file:
        csvreader = csv.DictReader(csvfile, delimiter=' ', quotechar='|')
```
Should "csv_file" be "csvfile"?

**Comment by loomcode** [comment]
Also, why is the default csv delimiter " "?

**Comment by quantumjot** [comment]
good catch, thanks! will get that fixed ASAP

**Comment by quantumjot** [comment]
I made a start on this, although it's not fully tested yet, and has not been pushed to PyPi either. In general, you can read more about data formats and how to use them in this colab notebook: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1V2TtJ5FGqSILTuThSRg5j9crsBsorUmy)

Let us know if this works (or not) for you. Tagging @KristinaUlicna re: documentation/bug fixes
