### ISSUE TITLE
Remove use of python keywords i.e. `property`

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/BayesianTracker#92]
Python keywords shouldn't be used as variables. Found here: https://github.com/quantumjot/BayesianTracker/blob/45edd65672db60ac32eba918bc3c31564685dd2e/btrack/utils.py#L334 but possibly also elsewhere

**Comment by quantumjot** [comment]
I think this one is done now: https://github.com/quantumjot/BayesianTracker/commit/a8c46bff6d55bb536b930a9672aa4d54fa00012b
