### ISSUE TITLE
Is `properties` here a `tuple` or a `dict`

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/BayesianTracker#93]
In this line `properties` is being used as a `dict` as its deleting the value from the `dict`
https://github.com/quantumjot/BayesianTracker/blob/45edd65672db60ac32eba918bc3c31564685dd2e/btrack/_localization.py#L210-L212

but at the top of `segmentation_to_objects` it is typed as a `tuple`
https://github.com/quantumjot/BayesianTracker/blob/45edd65672db60ac32eba918bc3c31564685dd2e/btrack/_localization.py#L146

**Comment by quantumjot** [comment]
Related #57
