### ISSUE TITLE
Process Covariance matrix Q missing in the cell_config.json file

### ISSUE THREAD

**Issue by kapoorlab** [quantumjot/BayesianTracker#96]
I noticed that the process covariance matrix Q that contains the position and velocity uncertainty is missing in the cell_config.json but appears in the [explanation of the parameters ](https://btrack.readthedocs.io/en/latest/user_guide/configuration.html). Is this intentional and the tracking is supposed to go well without including this matrix? It is supposed to update the state covariance matrix, P as P = APA^t + Q

**Comment by quantumjot** [comment]
Hi Varun,

Yes the tracker uses the process covariance matrix. You can specify it as **Q** or as **G**, where Q = G.T @ G.  I think the docstrings could use some extra detail on this matter 😄
